### ISSUE TITLE
Подписание вложений при подаче заявления при межведомственном взаимодействии

### ISSUE THREAD

**Issue by provorkova** [CodeInside/siu#12]
Возник вопрос при разработке сервиса межведомственного взаимодействия SID0003564, Сервис предоставления услуг Росреестра в электронном виде. Его особенностью является подача заявления в виде xml-файла с приложенной подписью физического лица в zip-пакете. 
Разбираясь с кодом СИУ я обнаружила, что подписание вложений реализуется в классе ru.codeinside.gws.core.Zip в методе toBinaryData(final Enclosure[] enclosures, CryptoProvider cryptoProvider)
Для того, чтобы вложения были подписаны, нужно добавить подпись в enclosure.signature. Но я не знаю, как в методе сервиса createClientRequest(ExchangeContext exchangeContext)
(класса, реализующего интерфейс ru.codeinside.gws.api.Client) получить значение подписи, чтобы добавить ее к вложению.

Был предложен другой вариант добавления файла подписи заявления: добавить в маршрут следующие задачи:
<serviceTask name="Подготовка запроса потребителем" activiti:expression="#{smev.prepare(execution, 'gws3564', 'request_data')}"/>

    <userTask name="Подпись запроса">
      <extensionElements>
        <activiti:formProperty id="request_data_enclosure_to_sign_vars" name="Данные для подписи" type="smevRequestEnclosure"/>
        <activiti:formProperty id="sign" name="Подпись" type="signature"/>
      </extensionElements>
    </userTask>

    <serviceTask name="Встраивание подписи в запрос и отправка" activiti:expression="#{smev.done(execution, 'gws3564', 'request_data')}"/>

В таком случае в методе ru.codeinside.gses.beans.Smev.createClientRequest(ClientRequestEntity entity, ExchangeContext context, String executionId, String variableName) возникает исключение IllegalStateException("Отсутсвуют данные для подписи"), хотя на интерфейсе подпись для заявления была добавлена. Исключение возникает по причине того, что auditValue.getSign() == null и auditValue.getCert()== null. 

На запросы приходит ответ 0010- Файл подписи заявления отсутствует в пакете. 

Прошу помочь мне разобраться с механизмом подписания заявления. Спасибо.

**Comment by GnusinPavel** [comment]
Добрый день.

Возможно у вас пропущен подготовительный этап перед подписью запроса (

    <userTask name="Подпись запроса">
):
    
    <serviceTask id="servicetask1" name="Подготовка запроса СМЭВ" activiti:expression="#{smev.prepare(execution, 'gws3564', 'request_data')}"></serviceTask>

в реализации метода #ru.codeinside.gws.api.Client.createClientRequest(ExchangeContext exchangeContext) вложения должны формироваться примерно так:

```java
final ClientRequest request = new ClientRequest();
....
String id = UUID.randomUUID().toString();
String xml = ...;  // формирование xml документа
String zipName = "req_" + id;
Enclosure enclosure = new Enclosure(zipName + ".xml", xml.getBytes());
enclosure.fileName = zipName + ".xml";
request.enclosures = new Enclosure[]{enclosure};
request.enclosureDescriptor = zipName;

**Comment by provorkova** [comment]
Здравствуйте.
Этап подготовки запроса в bpmn присутствует.
При формировании вложений, как я поняла, нужно  добавить 
request.signRequired = true;
иначе подписываться ничего не будет. Но, к сожалению, это не решает мою проблему. Подписания не происходит.

**Comment by GnusinPavel** [comment]
а вы задаете request.enclosureDescriptor как в куске кода выше?

**Comment by provorkova** [comment]
да

**Comment by GnusinPavel** [comment]
попробуйте убрать строку с 

     request.signRequired = true;

в данном случае если он true, то как раз и вылетает это исключение.

**Comment by provorkova** [comment]
Давайте разберемся с тем, что происходит в методе ru.codeinside.gses.beans.Smev.done(DelegateExecution execution, String serviceName, String variableName). 
Насколько я понимаю подписание должно происходить в методе createClientRequest(ClientRequestEntity entity, ExchangeContext context, String executionId, String variableName), а точнее в строке 
request.appData = cryptoProvider.inject(namespaces, appData, x509, sign). 
При этом мы видим, что в эту ветку мы перейдем только если entity.signRequired == true. И еще мы видим, что подписываться будет appData, а не сформированное заявление. 
Возможно я не права. Тогда объясните пожалуйста в каком месте ошибка в моих рассуждениях. Мне нужно понять к чему вообще стремиться - где происходит подписание, где находится подпись в тот момент, когда она загружена, как ее можно получить. 
Если убрать строку request.signRequired = true, то исключения не происходит. Просто возвращается ответ 0010- Файл подписи заявления отсутствует в пакете.

**Comment by GnusinPavel** [comment]
Подписание происходит в момент когда пользователь выбирает сертификат и тыкает подписать. В строке

    request.appData = cryptoProvider.inject(namespaces, appData, x509, sign). 

происходит не подписание, а встраивание подписи в блок appData. Тут просто неудачное наименование флага, и он не актуален сейчас. В данном случает подпись тут представляется как detached в формате pkc7, т.е. отдельный файл с расширением .sig и все это лежит в zip архиве с заявлением, блок BinaryData. Это делается в #ru.codeinside.gws.core.Xml.addMessageData().

Проверьте в сформированном soap-запросе блок BinaryData. Там должен быть zip архив в формате base64, содержащий как раз xml-файл с заявлением и файл с подписью.

**Comment by provorkova** [comment]
Добрый день.
В предложенном Вами решении подписания, ЭП-СП прикрепляет исполнитель, тоесть совсем не тот человек, который отправляет запрос. Позволяет ли СИУ подписывать вложения заявителем?

**Comment by GnusinPavel** [comment]
День добрый. Кого вы имеете ввиду под заявителем? Если роль пользователя в СИУ, то да, он может подписывать заявление и все вложения, если на форме присутствует поле для подписи, то будут подписаны все поля.

  <activiti:formProperty id="signatureId" name="Личная подпись" type="signature" variable="signature" required="true"></activiti:formProperty>

**Comment by provorkova** [comment]
Да, речь про роль заявитель. На форме присутствует поле для подписи, но вложения не подписываются. Также в сервисе ФНС в AppData подпись не попадает, хотя это поле заполняется.

Добавлять подписание получилось только добавлением задач, связанных с подписанием в маршрут, но этот вариант нам не подходит, так как в таком случае подпись ставит не то лицо, которое инициировало запрос.

**Comment by GnusinPavel** [comment]
В таком случае заявитель должен быть еще и исполнителем. И исполнение заявки должно сразу назначаться на него.

    <startEvent id="startevent1" name="Start" activiti:initiator="appData_initiator">
    ...
    <userTask id="usertask1" name="Подпись запроса" activiti:assignee="${appData_initiator}">

**Comment by provorkova** [comment]
Нам не подходит вариант, когда заявитель и исполнитель одно лицо. Поэтому не могли бы вы помочь разобраться с подписанием при помощи поля
<activiti:formProperty id="signatureId" name="Личная подпись" type="signature" variable="signature"  required="true"></activiti:formProperty>

**Comment by GnusinPavel** [comment]
На данный момент заявитель может подписывать только данные формы на этапе подачи заявления. Сформированный xml-запрос он подписать не может.

**Comment by provorkova** [comment]
То есть нет никакой возможности привязать подпись, которая была добавлена при подаче заявления, к вложениям вручную из сервиса?

**Comment by GnusinPavel** [comment]
Что вы имеете ввиду под вложением? Файл выбираемый на форме? Или же сформированную заявку в виде xml-файла, которая передается как вложение в запросе?

**Comment by provorkova** [comment]
Вложением может являться и файл и заявка в виде xml, поэтому интересует работа и с тем и с другим.

**Comment by GnusinPavel** [comment]
прикрепленный файл с формы можно получить через #ru.codeinside.gws.api.ExchangeContext .getEnclosure. Если на форме было поле для подписи, то это вложение будет подписано. В поле signature будут значения подписи и сертификата.

**Comment by provorkova** [comment]
Дело в том, что поле signature при подаче заявления было заполнено, но в клиенте разрабатываемого сервиса в методе createClientRequest(ExchangeContext ctx) я не могу получить значение подписи. ctx.getVariable("signature") возвращает null.

**Comment by GnusinPavel** [comment]
вам надо получать не ctx.getVariable("signature"), а ctx.getEnclosure("myFormFile"). В полученной переменной и будет подпись в поле signature

**Comment by provorkova** [comment]
ясно, а без файла значение подписи не получить получается?

**Comment by GnusinPavel** [comment]
а зачем вам подпись без его содержимого? там подписывается не вся форма целиком а каждое поле отдельно. в случае файлов их подписи можно получить, в случае обычных полей - нет.

**Comment by provorkova** [comment]
для того, чтобы при формировании xml с заявлением прикрепить к нему подпись

**Comment by GnusinPavel** [comment]
так это ж подпись совершенно другого файла будет, она не будет валидной.

**Comment by provorkova** [comment]
ясно, значит у заявителя нет никаких шансов подписать подаваемую заявку.

**Comment by GnusinPavel** [comment]
именно так.

**Comment by provorkova** [comment]
У меня тогда еще другой вопрос - по сервису фнс-3793. Не смотря на то, что поле signature заполняется при подаче запроса, данные в AppData остались неподписанными. Может быть есть какой-то секрет для добавления подписи ЭП-СП?

**Comment by GnusinPavel** [comment]
значение поля signature на форме не предается в явном виде в контекст, оно нужно для того чтобы подписать каждое поле на форме, и получить его его можно для файлов. AppData формируется уже в реализации клиента и это происходит после завершения подачи заявления.

**Comment by provorkova** [comment]
Добрый день, Павел. Подскажите пожалуйста, что нужно сделать, чтобы подписалась AppData? Нужно так же как и для подписи заявления добавлять дополнительные задачи в маршрут?

**Comment by GnusinPavel** [comment]
Здравствуйте. Пока никак, это будет реализовано позже.

**Comment by provorkova** [comment]
Здравствуйте, Павел. У меня возник следующий вопрос. При запросе сведений из Росреестра необходимо приложить изображения разных документов. На форму для этих документов добавила поля с типом attachment, затем, как я понимаю, в xml запроса мне нужно указать наименования загруженных файлов, находящихся во вложении. Как можно получить названия этих вложений?

**Comment by maxim-zaytsev** [comment]
Добрый день. Мне кажется лучше этот вопрос обсудить в рамках новой задачи, чтобы сохранять структуру. Заведите, пожалуйста, её.

**Comment by provorkova** [comment]
https://github.com/CodeInside/siu/issues/14
