### ISSUE TITLE
Прикрепление файлов к заявлению при межведомственном взаимодействии

### ISSUE THREAD

**Issue by provorkova** [CodeInside/siu#14]
При запросе сведений из Росреестра необходимо приложить изображения разных документов. На форму для этих документов были добавлены поля с типом attachment.  Далее в xml с запросом необходимо указать наименования загруженных файлов, которые будут добавлены в zip-пакет. Как можно получить наименования загруженных файлов?

**Comment by GnusinPavel** [comment]
Здравствуйте. Имена можно найти в #ru.codeinside.gws.api.Enclosure.fileName. Вложение получается через #ru.codeinside.gws.api.ExchangeContext.getEnclosure
