### ISSUE TITLE
Исключение IllegalStateException: Client not found! при отправлении запросов в СМЭВ

### ISSUE THREAD

**Issue by provorkova** [CodeInside/siu#16]
Добрый день. 
Вопрос по разработке сервиса межведомственного взаимодействия SID0003564, Сервис предоставления услуг Росреестра в электронном виде.
При отправлении запросов в методе smev.call(execution, ‘er-rr3564’) возникает исключение IllegalStateException: Client not found! При этом происходит прерывание пинга, а заявка в список ошибочных не попадает (на владке «Управление вызовами СМЭВ» заявки с таким номером нет). Данное исключение появляется во всех сервисах, но в других сервисах оно не было критичным. В связи с этим возникло два вопроса:
1.	Как избавиться от исключения IllegalStateException: Client not found!
2.	Что необходимо сделать, чтоб заявка, в которой произошло исключение на этапе отправления запроса появилась в таблице с ошибочными заявками на вкладке управление вызовами СМЭВ? В данный момент получается, что заявка просто теряется.

server.log: http://pastebin.ru/nPP5djz1

С уважением, Проворкова Наталия

**Comment by maxim-zaytsev** [comment]
er-rr3564 - это правильное имя сервиса? сконфигурирован в панели администратора верно?

**Comment by provorkova** [comment]
да, так как запрос успешно отправился

**Comment by maxim-zaytsev** [comment]
покажите скриншот панели редактирования параметров сервиса

**Comment by provorkova** [comment]
![screenshot - 15 05 2015 - 11_35_42](https://cloud.githubusercontent.com/assets/11819175/7649585/03744bc8-faf7-11e4-87e9-bbbb2ca6521d.png)

**Comment by dmitry-titov** [comment]
Добрый день. Попробуйте использовать managedCall вместо call, чтобы понять причину ошибки.
https://github.com/CodeInside/siu/wiki/Разработка-сервисов-потребителей#Обработка-ошибок-асинхронного-сервиса

**Comment by provorkova** [comment]
Здравствуйте, при использовании managedCall в переменную call_error записывается строка "er-rr3564" managedCall error java.lang.IllegalStateException: Client not found! [er-rr3564]

**Comment by dmitry-titov** [comment]
Пришлите, пожалуйста, список модулей glassfish, через команду asadmin list-components, а также скриншот вкладки Applications из панели администратора glassfish

**Comment by provorkova** [comment]
![glass_admin_applications](https://cloud.githubusercontent.com/assets/11819175/7749773/926e2b7e-ffd8-11e4-93d5-751a8771cacd.png)
![siu_admin_rr-3564](https://cloud.githubusercontent.com/assets/11819175/7749772/926c2414-ffd8-11e4-8835-198da522754b.png)
![list-components](https://cloud.githubusercontent.com/assets/11819175/7749781/9c766500-ffd8-11e4-9be0-735249a31013.jpg)

**Comment by dmitry-titov** [comment]
Модули, которые устанавливаются в системе, должны иметь тип osgi.
Выгрузите установленные модули СИУ через команду undeploy и заново установите, указав тип osgi. Это можно сделать из панели администратора glassfish или через консоль.
пример:
asadmin deploy --port 4848 --availabilityenabled=true --name=web-client-1.1.3 --type=osgi --target=server "web-client-1.1.3.jar"

**Comment by provorkova** [comment]
Спасибо за ответ
