### ISSUE TITLE
Получение списка процедур (их кодов)

### ISSUE THREAD

**Issue by KingAir** [CodeInside/siu#17]
Здравствуйте! Разрабатываю модуль-сервис, который должен запускать процедуры. При попытке создать процедуру через  ctx.getDeclarerContext(procedureCode), пишет, что процедуры с таким кодом не найдено, хотя в веб-морде их видно (в административных процедурах). Возможно нужно как то по другому запускать процедуры? Есть ли возможность (через методы) посмотреть список зарегистрированных процедур и их кодов? Спасибо!

**Comment by dmitry-titov** [comment]
Добрый день. Можете уточнить, что представляет из себя сервис - потребитель, поставщик услуги. getDeclarerContext - не создает процедуру, а создает контекст подачи заявления, процедура должна уже существовать к этому времени. Данный

**Comment by KingAir** [comment]
Сервис - поставщик услуги. Собсно вопрос по поводу как запускать - уже не актуален, разобрались. Вопрос остался один: есть ли возможность посмотреть список зарегистрированных процедур.

**Comment by dmitry-titov** [comment]
Через API такой возможности нет. Сейчас получить список можно только через sql-запрос.
