### ISSUE TITLE
Доступ к справочникам

### ISSUE THREAD

**Issue by KingAir** [CodeInside/siu#19]
Доброго времени суток! Есть ли возможность из кода (сервиса) достучаться к справочникам? Получить их список? Обратиться к конкретному справочнику? Спасибо!

**Comment by dmitry-titov** [comment]
Для получения справочника можно использовать ru.codeinside.gws.api.Internals 
в описателе компонентов добавить блок
< component >
...
  < reference name="internals"
             interface="ru.codeinside.gws.api.Internals"
             cardinality="1..1"
             policy="dynamic"
             bind="bindInternals"
             unbind="unbindInternals"
    / >
...
</ component >

Возможность получения списка справочников не реализована.

**Comment by KingAir** [comment]
Спасибо!
