### ISSUE TITLE
Заполнение наименования организации заявителя

### ISSUE THREAD

**Issue by provorkova** [CodeInside/siu#20]
Добрый день!
Подскажите пожалуйста, каким образом в классе, имплементирующем  ru.codeinside.gws.api.Client, при создании запроса, можно узнать наименование организации, в которой состоит заявитель?

С уважением, Наталия Проворкова

**Comment by GnusinPavel** [comment]
Добрый день! Для этого можно использовать бин ru.codeinside.gses.beans.filevalues.Users

**Comment by provorkova** [comment]
Подскажите пожалуйста, что необходимо сделать, чтобы получилась инъекця этого бина в клиент сервиса? При сборке модуля получаю ошибку package ru.codeinside.gses.beans.filevalues does not exist.

**Comment by GnusinPavel** [comment]
Он не инжекстится в объек, он вызывается из BPMN-скрипта. Там же комментарий указан.

**Comment by provorkova** [comment]
Понятно, тогда нужен пример вызова метода из scriptTask

**Comment by dmitry-titov** [comment]
В BPMN маршруте используется ServiceTask, в нём:
Task type - expression
Expression -  #{users.orgName('логин_пользователя')}
Result variable - organizationName
Затем organizationName или подставляется в пакет xml как (String) ctx.getVariable("organizationName") , или передается на UserTask в Varialble.

**Comment by provorkova** [comment]
Спасибо
