### ISSUE TITLE
Обновление интерфейса (не работает)

### ISSUE THREAD

**Issue by KingAir** [CodeInside/siu#21]
При тестировании сервисов было замечено, что новые заявки (отправленные например через soapui) не появляются в интерфейсе автоматически, даже при обновлении страницы. Чтобы увидеть новые заявки, нужно выйти (логофф) и снова зайти. Подобное поведение замечено и у логов. Возможно, содержимое виджетов автоматически, но через какое-то время? Если нет, то как пользователям понять, что пришли новые заявки?

**Comment by ksumuratova** [comment]
Пробовали обновляться с помощью кнопки "Обновить список заявок" в фильтре? 
![update](https://cloud.githubusercontent.com/assets/2510660/8107199/45905b78-1050-11e5-9861-9c93a0ee27d0.png)

**Comment by KingAir** [comment]
Спасибо, с заявками разобрались. Что насчет логов?

**Comment by ksumuratova** [comment]
Логи должны обновляться в автоматическом режиме. 
Логирование ведется только модулей, которые есть в системе. А со стороны поставщика нужно проверить, что включен флаг в колонке "Журнал" на вкладке Сервисы информационных систем - Поставщики

**Comment by KingAir** [comment]
Не работает в автоматическом режиме. Регистрирую сервис, ставлю галочку "Журнал", перехожу на закладку "Логи". Посылаю через soapui запрос, приходит положительный ответ. В логах ничего не появляется, попытка обновить страницу тоже не помогает. Только после логоффа логи обновляются.

**Comment by dmitry-titov** [comment]
Некорректно выразились по поводу автоматического режима. Если на вкладке нет кнопки "Обновить", то обновление работает только когда меняется вкладка или пользователь вышел и снова зашел. Попытка простого обновления страницы в этом случае положительного результата не даст.

**Comment by KingAir** [comment]
Смена вкладки не дает результата.
