### ISSUE TITLE
Серый IP адрес в WSDL сервиса

### ISSUE THREAD

**Issue by KingAir** [CodeInside/siu#23]
Доброго времени суток! Пытаемся отправить 390 сервис (о привлечении иностр  работников) на регистрацию в смэв. Сервис доступен по адресу http://gutest.yarcloud.ru/smev/foreign-worker-1022/?wsdl. Однако если посмотреть код в браузере этой wsdl видно, что адреса к xsd и сервису подставлены неверно - вместо gutest.yarcloud.ru стоит серый ip адрес. Например, в исходном коде wsdl путь к xsd выглядит как: 
xs:import namespace="http://smev.gosuslugi.ru/rev111111" schemaLocation="smevMessageData.xsd
уже в развернутом сервисе путь к xsd такой: 
xs:import namespace="http://smev.gosuslugi.ru/rev111111" schemaLocation="http://10.188.3.15:80/smev/foreign-worker-1022/?xsd=2
Получается, что внешние пользователи не могут достучаться до xsd'шек сервиса. Кто подставляет адреса к файлам xsd и как настроить такое поведение?

**Comment by ksumuratova** [comment]
Добрый день! xsd скорее всего относительно прописаны, и доступность настраивается проксирующим сервером, как возможный вариант ошибки.
Сам сервис чуть позже посмотрит специалист ОЭП

**Comment by KingAir** [comment]
Указать абсолютный путь в WSDL не получилось - зависает список поставщиков (http://glassfish_serv/smev/) и в логах глассфиша пишет timeout. Просим на примере 390 сервиса показать, как правильно оформить WSDL , чтобы XSD имели абсолютный путь с "белым" ip адресом.

**Comment by KingAir** [comment]
Проблема оказалась в настройках http сервера, админы разобрались.
